"""Generate platform-specific agent files from home/agents/*.md + model-map.yaml."""

from __future__ import annotations

import sys
from pathlib import Path

from sync.common import (
    parse_frontmatter,
    parse_model_map,
    prune_stale_md,
    repo_home,
    write_text_if_changed,
)

AGENTS_DIR = repo_home() / "agents"
MAP_PATH = AGENTS_DIR / "model-map.yaml"
CLAUDE_OUT = repo_home() / ".claude" / "agents"
CURSOR_OUT = repo_home() / ".cursor" / "agents"

GENERATED_BANNER = (
    "<!-- Generated by home/sync/sync — edit sources in home/agents/, "
    "not this file. -->\n"
)


def split_agent(path: Path) -> tuple[dict[str, str], str]:
    return parse_frontmatter(path, require={"tier", "name"})


def _emit_field(key: str, value: str) -> str:
    if "\n" in value or value.startswith(">-") or (len(value) > 80 and " " in value):
        if value.startswith(">-\n") or "\n" in value:
            body_lines = value.split("\n")
            out = [f"{key}: >-"]
            for bl in body_lines:
                if bl == "":
                    out.append("")
                elif bl.startswith("  "):
                    out.append(bl)
                else:
                    out.append(f"  {bl}")
            return "\n".join(out)
        return f"{key}: >-\n  " + value.replace("\n", "\n  ")
    return f"{key}: {value}"


def render_frontmatter(fields: dict[str, str], model: str) -> str:
    lines = ["---"]
    order = ["name", "description", "model", "disallowedTools", "readonly", "is_background"]
    emitted: set[str] = set()
    for key in ("name", "description"):
        if key in fields:
            lines.append(_emit_field(key, fields[key]))
            emitted.add(key)
    lines.append(f"model: {model}")
    emitted.add("model")
    for key in order:
        if key in fields and key not in emitted and key != "tier":
            lines.append(_emit_field(key, fields[key]))
            emitted.add(key)
    for key, val in fields.items():
        if key in emitted or key == "tier":
            continue
        lines.append(_emit_field(key, val))
    lines.append("---")
    return "\n".join(lines) + "\n"


def write_agent(out_dir: Path, name: str, fields: dict[str, str], body: str, model: str) -> bool:
    """Render and write an agent file. Returns True if the file changed."""
    body_out = body if body.startswith("\n") else "\n" + body
    content = render_frontmatter(fields, model) + GENERATED_BANNER + body_out
    if not content.endswith("\n"):
        content += "\n"
    path = out_dir / f"{name}.md"
    return write_text_if_changed(path, content)


def sync_agents() -> int:
    """Generate Claude/Cursor agent pins from sources. Catalog/live-install: conveyor."""
    if not MAP_PATH.is_file():
        print(f"missing {MAP_PATH}", file=sys.stderr)
        return 1
    tiers = parse_model_map(MAP_PATH)
    sources = sorted(p for p in AGENTS_DIR.glob("*.md") if p.name != "README.md")
    if not sources:
        print(f"no agent sources in {AGENTS_DIR}", file=sys.stderr)
        return 1

    keep: set[str] = set()
    written = 0
    for src in sources:
        fields, body = split_agent(src)
        tier = fields["tier"].strip()
        if tier not in tiers:
            print(f"{src}: unknown tier {tier!r}; known: {sorted(tiers)}", file=sys.stderr)
            return 1
        name = fields["name"].strip()
        keep.add(src.stem)
        keep.add(name)
        changed = write_agent(CLAUDE_OUT, name, fields, body, tiers[tier]["claude"])
        changed = write_agent(CURSOR_OUT, name, fields, body, tiers[tier]["cursor"]) or changed
        if changed:
            written += 1
            print(
                f"  {name}: tier={tier} → "
                f"claude={tiers[tier]['claude']} cursor={tiers[tier]['cursor']}"
            )

    unchanged = len(sources) - written
    if unchanged:
        print(f"  ({unchanged} agents unchanged)")

    for out_dir in (CLAUDE_OUT, CURSOR_OUT):
        prune_stale_md(out_dir, keep, relative_to=repo_home())

    print(
        f"synced {len(sources)} agents → "
        f"{CLAUDE_OUT.relative_to(repo_home().parent)} + "
        f"{CURSOR_OUT.relative_to(repo_home().parent)}"
    )
    return 0


def main() -> int:
    return sync_agents()


if __name__ == "__main__":
    raise SystemExit(main())
