"""Generate platform-specific agent files from home/agents/*.md + model-map.yaml."""

from __future__ import annotations

import re
import sys
from pathlib import Path

from sync.catalog import generate_catalog
from sync.common import (
    FRONTMATTER_RE,
    parse_model_map,
    prune_stale_md,
    repo_home,
)
from sync.live_cursor import install_all as live_install

AGENTS_DIR = repo_home() / "agents"
MAP_PATH = AGENTS_DIR / "model-map.yaml"
CLAUDE_OUT = repo_home() / ".claude" / "agents"
CURSOR_OUT = repo_home() / ".cursor" / "agents"

GENERATED_BANNER = (
    "<!-- Generated by home/agents/sync-agents — edit sources in home/agents/, "
    "not this file. -->\n"
)


def split_agent(path: Path) -> tuple[dict[str, str], str]:
    text = path.read_text()
    m = FRONTMATTER_RE.match(text)
    if not m:
        raise SystemExit(f"{path}: missing YAML frontmatter")
    fm_raw, body = m.group(1), m.group(2)
    fields: dict[str, str] = {}
    key: str | None = None
    buf: list[str] = []

    def flush() -> None:
        nonlocal key, buf
        if key is None:
            return
        fields[key] = "\n".join(buf).rstrip("\n")
        key = None
        buf = []

    for line in fm_raw.splitlines():
        if line.startswith("  ") and key is not None:
            buf.append(line)
            continue
        kv = re.match(r"^([A-Za-z0-9_]+):\s*(.*)$", line)
        if kv:
            flush()
            key = kv.group(1)
            rest = kv.group(2)
            if rest in (">-", "|"):
                buf = []
            else:
                buf = [rest]
            continue
        if key is not None and (line.startswith(" ") or line == ""):
            buf.append(line)
            continue
        raise SystemExit(f"{path}: cannot parse frontmatter line: {line!r}")
    flush()
    if "tier" not in fields:
        raise SystemExit(f"{path}: missing required `tier` field")
    if "name" not in fields:
        raise SystemExit(f"{path}: missing required `name` field")
    return fields, body


def _emit_field(key: str, value: str) -> str:
    if "\n" in value or value.startswith(">-") or (len(value) > 80 and " " in value):
        if value.startswith(">-\n") or "\n" in value:
            body_lines = value.split("\n")
            out = [f"{key}: >-"]
            for bl in body_lines:
                if bl == "":
                    out.append("")
                elif bl.startswith("  "):
                    out.append(bl)
                else:
                    out.append(f"  {bl}")
            return "\n".join(out)
        return f"{key}: >-\n  " + value.replace("\n", "\n  ")
    return f"{key}: {value}"


def render_frontmatter(fields: dict[str, str], model: str) -> str:
    lines = ["---"]
    order = ["name", "description", "model", "disallowedTools", "readonly", "is_background"]
    emitted: set[str] = set()
    for key in ("name", "description"):
        if key in fields:
            lines.append(_emit_field(key, fields[key]))
            emitted.add(key)
    lines.append(f"model: {model}")
    emitted.add("model")
    for key in order:
        if key in fields and key not in emitted and key != "tier":
            lines.append(_emit_field(key, fields[key]))
            emitted.add(key)
    for key, val in fields.items():
        if key in emitted or key == "tier":
            continue
        lines.append(_emit_field(key, val))
    lines.append("---")
    return "\n".join(lines) + "\n"


def write_agent(out_dir: Path, name: str, fields: dict[str, str], body: str, model: str) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    body_out = body if body.startswith("\n") else "\n" + body
    content = render_frontmatter(fields, model) + GENERATED_BANNER + body_out
    if not content.endswith("\n"):
        content += "\n"
    path = out_dir / f"{name}.md"
    path.write_text(content)
    return path


def sync_agents(*, install_live: bool = True) -> int:
    if not MAP_PATH.is_file():
        print(f"missing {MAP_PATH}", file=sys.stderr)
        return 1
    tiers = parse_model_map(MAP_PATH)
    sources = sorted(p for p in AGENTS_DIR.glob("*.md") if p.name != "README.md")
    if not sources:
        print(f"no agent sources in {AGENTS_DIR}", file=sys.stderr)
        return 1

    for src in sources:
        fields, body = split_agent(src)
        tier = fields["tier"].strip()
        if tier not in tiers:
            print(f"{src}: unknown tier {tier!r}; known: {sorted(tiers)}", file=sys.stderr)
            return 1
        name = fields["name"].strip()
        write_agent(CLAUDE_OUT, name, fields, body, tiers[tier]["claude"])
        write_agent(CURSOR_OUT, name, fields, body, tiers[tier]["cursor"])
        print(
            f"  {name}: tier={tier} → "
            f"claude={tiers[tier]['claude']} cursor={tiers[tier]['cursor']}"
        )

    keep = {p.stem for p in sources}
    # Prefer name from frontmatter when it differs from filename.
    keep |= {
        split_agent(p)[0]["name"].strip()
        for p in sources
    }
    for out_dir in (CLAUDE_OUT, CURSOR_OUT):
        prune_stale_md(out_dir, keep, relative_to=repo_home())

    generate_catalog()

    if install_live:
        # Default one-shot path: agents + Cursor rule/hooks/cli (commands via
        # sync-commands). machine_setup uses --no-live + live-install instead.
        live_install(
            agents=True,
            commands=False,
            hooks=True,
            rule=True,
            cli_config=True,
        )

    print(
        f"synced {len(sources)} agents → "
        f"{CLAUDE_OUT.relative_to(repo_home().parent)} + "
        f"{CURSOR_OUT.relative_to(repo_home().parent)}"
    )
    return 0


def main() -> int:
    return sync_agents(install_live=True)


if __name__ == "__main__":
    raise SystemExit(main())
