"""Generate tier catalog artifacts from agent/command sources + model-map."""

from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

from sync.common import FRONTMATTER_RE, parse_model_map, replace_marked_section, repo_home

AGENTS_DIR = repo_home() / "agents"
COMMANDS_DIR = repo_home() / "commands"
MAP_PATH = AGENTS_DIR / "model-map.yaml"
CURSOR_RULE = repo_home() / ".cursor" / "rules" / "subagent-model-fallback.mdc"
CURSOR_ROUTING_RULE = repo_home() / ".cursor" / "rules" / "agent-routing.mdc"
CLAUDE_MD = repo_home() / ".claude" / "CLAUDE.md"
COMMANDS_README = COMMANDS_DIR / "README.md"

BEGIN_AGENTS = "<!-- BEGIN GENERATED AGENT TIER TABLE -->"
END_AGENTS = "<!-- END GENERATED AGENT TIER TABLE -->"
BEGIN_COMMANDS = "<!-- BEGIN GENERATED COMMAND TIER TABLE -->"
END_COMMANDS = "<!-- END GENERATED COMMAND TIER TABLE -->"
BEGIN_MAP = "<!-- BEGIN GENERATED MODEL MAP TABLE -->"
END_MAP = "<!-- END GENERATED MODEL MAP TABLE -->"
BEGIN_ROUTING = "<!-- BEGIN GENERATED AGENT ROUTING -->"
END_ROUTING = "<!-- END GENERATED AGENT ROUTING -->"


def _simple_frontmatter_fields(path: Path) -> dict[str, str]:
    text = path.read_text()
    m = FRONTMATTER_RE.match(text)
    if not m:
        raise SystemExit(f"{path}: missing YAML frontmatter")
    fields: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if not line.strip() or line.startswith(" "):
            continue
        kv = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if kv:
            fields[kv.group(1)] = kv.group(2).strip()
    return fields


def load_agent_tiers() -> dict[str, list[str]]:
    by_tier: dict[str, list[str]] = defaultdict(list)
    for src in sorted(AGENTS_DIR.glob("*.md")):
        if src.name == "README.md":
            continue
        fields = _simple_frontmatter_fields(src)
        name = fields.get("name") or src.stem
        tier = fields.get("tier")
        if not tier:
            raise SystemExit(f"{src}: missing tier")
        by_tier[tier.strip()].append(name.strip())
    return {k: sorted(v) for k, v in by_tier.items()}


def load_command_tiers() -> dict[str, list[str]]:
    by_tier: dict[str, list[str]] = defaultdict(list)
    for src in sorted(COMMANDS_DIR.glob("*.md")):
        if src.name == "README.md":
            continue
        fields = _simple_frontmatter_fields(src)
        tier = fields.get("tier")
        if not tier:
            raise SystemExit(f"{src}: missing tier")
        by_tier[tier.strip()].append(f"/{src.stem}")
    return {k: sorted(v) for k, v in by_tier.items()}


def render_agent_tier_table(tiers: dict[str, dict[str, str]], agents: dict[str, list[str]]) -> str:
    lines = [
        "| Tier | Agents | Claude Code | Cursor |",
        "| --- | --- | --- | --- |",
    ]
    for tier in ("cheap", "mid", "strong"):
        names = ", ".join(f"`{n}`" for n in agents.get(tier, []))
        pins = tiers[tier]
        lines.append(
            f"| {tier} | {names} | `{pins['claude']}` | `{pins['cursor']}` |"
        )
    return "\n".join(lines)


def render_command_tier_table(commands: dict[str, list[str]]) -> str:
    lines = [
        "| Tier | Commands |",
        "| --- | --- |",
    ]
    for tier in ("cheap", "mid", "strong"):
        names = commands.get(tier, [])
        if not names:
            continue
        lines.append(f"| {tier} | {', '.join(f'`{n}`' for n in names)} |")
    return "\n".join(lines)


def render_model_map_table(tiers: dict[str, dict[str, str]]) -> str:
    lines = [
        "| Tier | Claude Code (`model:`) | Cursor (preferred session model) |",
        "| --- | --- | --- |",
    ]
    for tier in ("cheap", "mid", "strong"):
        pins = tiers[tier]
        lines.append(f"| {tier} | `{pins['claude']}` | `{pins['cursor']}` |")
    return "\n".join(lines)


def render_cursor_mdc(
    tiers: dict[str, dict[str, str]], agents: dict[str, list[str]]
) -> str:
    all_names = []
    for tier in ("cheap", "mid", "strong"):
        all_names.extend(agents.get(tier, []))
    names_csv = ", ".join(f"`{n}`" for n in all_names)
    strong = tiers["strong"]["cursor"]
    table_rows = []
    for tier in ("cheap", "mid", "strong"):
        names = ", ".join(f"`{n}`" for n in agents.get(tier, []))
        table_rows.append(f"| {tier} | {names} | `{tiers[tier]['cursor']}` |")
    table = "\n".join(
        [
            "| Tier | Agents | Model |",
            "| --- | --- | --- |",
            *table_rows,
        ]
    )
    return f"""---
description: Subagent model pins and rate-limit fallback to auto
alwaysApply: true
---

<!-- Generated by home/sync/catalog.py — edit sources in home/agents/, not this file. -->

# Subagent model routing (Cursor)

Custom subagents live in `~/.cursor/agents/` (generated from `~/agents/`). Prefer
them by name when the task matches: {names_csv}.

When choosing whom to spawn (or whether to stay in the parent), read the
`route-agents` skill (`~/.cursor/skills/route-agents/SKILL.md`).

Pinned models (from the agent frontmatter):

{table}

`boba-watcher` stays cheap for routine ticks. If it returns `STATUS: WAITING — ESCALATE`,
`/watch-boba` may re-spawn it **once** with the strong pin (`{strong}`
or `auto`). Scope/approach unblock drafts from `/watch-boba` also use the strong
model. Do not upgrade the whole watch loop.

## Rate-limit / quota fallback

If spawning a custom subagent fails because the pinned model is rate-limited,
out of quota, unavailable, or returns a plan/usage error:

1. Retry **once** with the same subagent but model `auto` (or omit `model` so it
   inherits / uses Auto).
2. If the retry also fails, surface the error — do not keep retrying or silently
   swap to an unrelated model.
3. Do **not** fall back to `auto` for ordinary task failures (bad prompt, tool
   errors, wrong agent choice). Only for model availability / usage limits.
"""


def render_agent_routing_body(agents: dict[str, list[str]]) -> str:
    """Hard must-not routing shared by Cursor rule + Claude CLAUDE.md section."""
    all_names = []
    for tier in ("cheap", "mid", "strong"):
        all_names.extend(agents.get(tier, []))
    names_csv = ", ".join(f"`{n}`" for n in all_names)
    return f"""# Agent routing (hard)

Pinned agents: {names_csv}.

Whom-table detail: `route-agents` skill. These rules are **must-nots** — treat
violations as errors, not style nits.

## Free-form prompt intake

A free-form request that names a Jira ticket (URL, key, or phrasing like
"investigate/fix this issue") is **not** an invitation for the parent to absorb
all the work. It is a prompt to enter the spine.

- Extract the Jira key and route to `/dispatch <KEY>` (default mode A) or
  `/ship <KEY>` (mode B) when the user asks to investigate, fix, or implement a
  ticket. Do not run a manual code search, edit, or PR opening in the parent.
- If you are already on a `<KEY>-...` branch with uncommitted or unpushed work
  and the user says they are done, route to `/wrap-up` to close the spine and
  open the PR — do not make them re-enter `/open-pr` manually.
- Only stay in the parent for genuine ad-hoc questions (no ticket, no
  implementation intent, no branch context) or explicit "explain" requests.

This keeps the parent interface thin and puts the deep work behind the spine's
pinned, tiered agents.

## Locate / explain / research

- Repo locate or compact gather → spawn **`scout`** (cheap).
- Subsystem walkthrough / architecture map → spawn **`scout-explain`** (mid).
- Spike / research-ticket prep (web, ticket comments, hypotheses) → spawn
  **`researcher`** (cheap).
- **Never** spawn builtin `Explore`, `generalPurpose`, `general-purpose`, or an
  untyped Task/Agent for those jobs. If the pinned agent fails to start, surface
  the error — do not silently fall back to a builtin explorer (model `auto`
  retry once still uses the **same** pinned agent name).
- Cursor Task/`subagent_type` often only lists **project-agents** under
  `<git-root>/.cursor/agents/` (not `~/.cursor/agents/`). If a pinned name is
  rejected as an invalid enum value: run `home/sync/ensure-project-agents` (or
  open a coding-agent launcher, which ensures best-effort), confirm the
  symlinks exist, then start a **new** Agent session so the Task enum reloads.
  Still never fall back to Explore/`generalPurpose`.

## Commit / land

- Parent **must not** run `git commit` (or equivalent staging+commit plumbing).
- Behavior-changing / runtime-surface work → **`/land`** (verifier → committer →
  handoff).
- Docs / comments / types / renames / formatting only → spawn **`committer`**
  directly.
- **`worker` must not commit.** Keep worker spawn prompts thin (spec + paths);
  never instruct the worker to commit.
- On `/land` (or any parent-run verifier gate): **obvious** `VERDICT: BREAKS`
  (concrete repro + mechanical/live-install fix, no design fork) → auto-repair
  and re-verify (≤3 cycles) without waiting for `go`. Non-obvious or
  budget-exhausted BREAKS still `HALT`.

## Mechanical cleanup + review

- Clear tsc/lint/formatter loops → spawn **`sweep`** (not parent/strong).
- PRs awaiting *your* review → **`/review-requests`** → **`pr-reviewer`**.
  Ad-hoc diff critique in a coding session may use the `code-review` skill.

## Terminal contracts

- Require each agent's terminal line (`ADVANCE` / `HALT` / `VERDICT:` /
  `STATUS:` as defined in that agent).
- If the reply is missing the required terminal line, treat it as
  `HALT: missing terminal contract` and do **not** continue the spine.
- `sweep`: `ADVANCE → /land` when on the pre-land conveyor; `ADVANCE → done`
  when the parent only asked to clean the tree; else `HALT:`.

## Security-review triage

Push-time security review findings (e.g. from the security-guidance plugin) are
not a parent context-switch. The parent already opened the PR; deeper
investigation of out-of-scope or pre-existing code belongs in the async tail.

- If the finding is for code this work did not touch, acknowledge it briefly and
  route it to `/babysit-pr <number>` or a security inbox for triage — do not
  investigate, blame, or propose fixes in the parent session.
- If the finding is for code this work touched, surface it as a `HALT:` and
  hand the fix back to `worker` through the normal spine.
- Never let a post-push security notification re-open the PR opening gate.
"""


def render_cursor_routing_mdc(agents: dict[str, list[str]]) -> str:
    body = render_agent_routing_body(agents)
    return f"""---
description: Hard agent routing — scout not Explore; committer/land not parent commit
alwaysApply: true
---

<!-- Generated by home/sync/catalog.py — edit catalog.py, not this file. -->

{body}
"""


def generate_catalog() -> None:
    if not MAP_PATH.is_file():
        raise SystemExit(f"missing {MAP_PATH}")
    tiers = parse_model_map(MAP_PATH)
    agents = load_agent_tiers()
    commands = load_command_tiers()

    CURSOR_RULE.parent.mkdir(parents=True, exist_ok=True)
    CURSOR_RULE.write_text(render_cursor_mdc(tiers, agents))
    print(f"  wrote {CURSOR_RULE.relative_to(repo_home().parent)}")

    CURSOR_ROUTING_RULE.write_text(render_cursor_routing_mdc(agents))
    print(f"  wrote {CURSOR_ROUTING_RULE.relative_to(repo_home().parent)}")

    agent_table = render_agent_tier_table(tiers, agents)
    if CLAUDE_MD.is_file() and replace_marked_section(
        CLAUDE_MD, BEGIN_AGENTS, END_AGENTS, agent_table
    ):
        print(f"  updated agent table in {CLAUDE_MD.relative_to(repo_home().parent)}")
    elif CLAUDE_MD.is_file():
        # Markers missing — still ok if already current via other means
        if BEGIN_AGENTS not in CLAUDE_MD.read_text():
            print(f"  warning: {CLAUDE_MD} missing {BEGIN_AGENTS}", flush=True)

    routing_body = render_agent_routing_body(agents).strip()
    if CLAUDE_MD.is_file() and replace_marked_section(
        CLAUDE_MD, BEGIN_ROUTING, END_ROUTING, routing_body
    ):
        print(f"  updated agent routing in {CLAUDE_MD.relative_to(repo_home().parent)}")
    elif CLAUDE_MD.is_file() and BEGIN_ROUTING not in CLAUDE_MD.read_text():
        print(f"  warning: {CLAUDE_MD} missing {BEGIN_ROUTING}", flush=True)

    cmd_table = render_command_tier_table(commands)
    if CLAUDE_MD.is_file() and replace_marked_section(
        CLAUDE_MD, BEGIN_COMMANDS, END_COMMANDS, cmd_table
    ):
        print(f"  updated command table in {CLAUDE_MD.relative_to(repo_home().parent)}")

    map_table = render_model_map_table(tiers)
    if COMMANDS_README.is_file() and replace_marked_section(
        COMMANDS_README, BEGIN_MAP, END_MAP, map_table
    ):
        print(f"  updated model map in {COMMANDS_README.relative_to(repo_home().parent)}")
    if COMMANDS_README.is_file() and replace_marked_section(
        COMMANDS_README, BEGIN_COMMANDS, END_COMMANDS, cmd_table
    ):
        print(
            f"  updated command tiers in {COMMANDS_README.relative_to(repo_home().parent)}"
        )
