"""Generate tier catalog artifacts from agent/command sources + model-map."""

from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path

from sync.common import FRONTMATTER_RE, parse_model_map, replace_marked_section, repo_home

AGENTS_DIR = repo_home() / "agents"
COMMANDS_DIR = repo_home() / "commands"
MAP_PATH = AGENTS_DIR / "model-map.yaml"
CURSOR_RULE = repo_home() / ".cursor" / "rules" / "subagent-model-fallback.mdc"
CLAUDE_MD = repo_home() / ".claude" / "CLAUDE.md"
COMMANDS_README = COMMANDS_DIR / "README.md"

BEGIN_AGENTS = "<!-- BEGIN GENERATED AGENT TIER TABLE -->"
END_AGENTS = "<!-- END GENERATED AGENT TIER TABLE -->"
BEGIN_COMMANDS = "<!-- BEGIN GENERATED COMMAND TIER TABLE -->"
END_COMMANDS = "<!-- END GENERATED COMMAND TIER TABLE -->"
BEGIN_MAP = "<!-- BEGIN GENERATED MODEL MAP TABLE -->"
END_MAP = "<!-- END GENERATED MODEL MAP TABLE -->"


def _simple_frontmatter_fields(path: Path) -> dict[str, str]:
    text = path.read_text()
    m = FRONTMATTER_RE.match(text)
    if not m:
        raise SystemExit(f"{path}: missing YAML frontmatter")
    fields: dict[str, str] = {}
    for line in m.group(1).splitlines():
        if not line.strip() or line.startswith(" "):
            continue
        kv = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if kv:
            fields[kv.group(1)] = kv.group(2).strip()
    return fields


def load_agent_tiers() -> dict[str, list[str]]:
    by_tier: dict[str, list[str]] = defaultdict(list)
    for src in sorted(AGENTS_DIR.glob("*.md")):
        if src.name == "README.md":
            continue
        fields = _simple_frontmatter_fields(src)
        name = fields.get("name") or src.stem
        tier = fields.get("tier")
        if not tier:
            raise SystemExit(f"{src}: missing tier")
        by_tier[tier.strip()].append(name.strip())
    return {k: sorted(v) for k, v in by_tier.items()}


def load_command_tiers() -> dict[str, list[str]]:
    by_tier: dict[str, list[str]] = defaultdict(list)
    for src in sorted(COMMANDS_DIR.glob("*.md")):
        if src.name == "README.md":
            continue
        fields = _simple_frontmatter_fields(src)
        tier = fields.get("tier")
        if not tier:
            raise SystemExit(f"{src}: missing tier")
        by_tier[tier.strip()].append(f"/{src.stem}")
    return {k: sorted(v) for k, v in by_tier.items()}


def render_agent_tier_table(tiers: dict[str, dict[str, str]], agents: dict[str, list[str]]) -> str:
    lines = [
        "| Tier | Agents | Claude Code | Cursor |",
        "| --- | --- | --- | --- |",
    ]
    for tier in ("cheap", "mid", "strong"):
        names = ", ".join(f"`{n}`" for n in agents.get(tier, []))
        pins = tiers[tier]
        lines.append(
            f"| {tier} | {names} | `{pins['claude']}` | `{pins['cursor']}` |"
        )
    return "\n".join(lines)


def render_command_tier_table(commands: dict[str, list[str]]) -> str:
    lines = [
        "| Tier | Commands |",
        "| --- | --- |",
    ]
    for tier in ("cheap", "mid", "strong"):
        names = commands.get(tier, [])
        if not names:
            continue
        lines.append(f"| {tier} | {', '.join(f'`{n}`' for n in names)} |")
    return "\n".join(lines)


def render_model_map_table(tiers: dict[str, dict[str, str]]) -> str:
    lines = [
        "| Tier | Claude Code (`model:`) | Cursor (preferred session model) |",
        "| --- | --- | --- |",
    ]
    for tier in ("cheap", "mid", "strong"):
        pins = tiers[tier]
        lines.append(f"| {tier} | `{pins['claude']}` | `{pins['cursor']}` |")
    return "\n".join(lines)


def render_cursor_mdc(
    tiers: dict[str, dict[str, str]], agents: dict[str, list[str]]
) -> str:
    all_names = []
    for tier in ("cheap", "mid", "strong"):
        all_names.extend(agents.get(tier, []))
    names_csv = ", ".join(f"`{n}`" for n in all_names)
    strong = tiers["strong"]["cursor"]
    table_rows = []
    for tier in ("cheap", "mid", "strong"):
        names = ", ".join(f"`{n}`" for n in agents.get(tier, []))
        table_rows.append(f"| {tier} | {names} | `{tiers[tier]['cursor']}` |")
    table = "\n".join(
        [
            "| Tier | Agents | Model |",
            "| --- | --- | --- |",
            *table_rows,
        ]
    )
    return f"""---
description: Subagent model pins and rate-limit fallback to auto
alwaysApply: true
---

<!-- Generated by home/sync/catalog.py — edit sources in home/agents/, not this file. -->

# Subagent model routing (Cursor)

Custom subagents live in `~/.cursor/agents/` (generated from `~/agents/`). Prefer
them by name when the task matches: {names_csv}.

When choosing whom to spawn (or whether to stay in the parent), read the
`route-agents` skill (`~/.cursor/skills/route-agents/SKILL.md`).

Pinned models (from the agent frontmatter):

{table}

`boba-watcher` stays mid for routine ticks. If it returns `STATUS: WAITING — ESCALATE`,
`/watch-boba` may re-spawn it **once** with the strong pin (`{strong}`
or `auto`). Scope/approach unblock drafts from `/watch-boba` also use the strong
model. Do not upgrade the whole watch loop.

## Rate-limit / quota fallback

If spawning a custom subagent fails because the pinned model is rate-limited,
out of quota, unavailable, or returns a plan/usage error:

1. Retry **once** with the same subagent but model `auto` (or omit `model` so it
   inherits / uses Auto).
2. If the retry also fails, surface the error — do not keep retrying or silently
   swap to an unrelated model.
3. Do **not** fall back to `auto` for ordinary task failures (bad prompt, tool
   errors, wrong agent choice). Only for model availability / usage limits.
"""


def generate_catalog() -> None:
    if not MAP_PATH.is_file():
        raise SystemExit(f"missing {MAP_PATH}")
    tiers = parse_model_map(MAP_PATH)
    agents = load_agent_tiers()
    commands = load_command_tiers()

    CURSOR_RULE.parent.mkdir(parents=True, exist_ok=True)
    CURSOR_RULE.write_text(render_cursor_mdc(tiers, agents))
    print(f"  wrote {CURSOR_RULE.relative_to(repo_home().parent)}")

    agent_table = render_agent_tier_table(tiers, agents)
    if CLAUDE_MD.is_file() and replace_marked_section(
        CLAUDE_MD, BEGIN_AGENTS, END_AGENTS, agent_table
    ):
        print(f"  updated agent table in {CLAUDE_MD.relative_to(repo_home().parent)}")
    elif CLAUDE_MD.is_file():
        # Markers missing — still ok if already current via other means
        if BEGIN_AGENTS not in CLAUDE_MD.read_text():
            print(f"  warning: {CLAUDE_MD} missing {BEGIN_AGENTS}", flush=True)

    cmd_table = render_command_tier_table(commands)
    if CLAUDE_MD.is_file() and replace_marked_section(
        CLAUDE_MD, BEGIN_COMMANDS, END_COMMANDS, cmd_table
    ):
        print(f"  updated command table in {CLAUDE_MD.relative_to(repo_home().parent)}")

    map_table = render_model_map_table(tiers)
    if COMMANDS_README.is_file() and replace_marked_section(
        COMMANDS_README, BEGIN_MAP, END_MAP, map_table
    ):
        print(f"  updated model map in {COMMANDS_README.relative_to(repo_home().parent)}")
    if COMMANDS_README.is_file() and replace_marked_section(
        COMMANDS_README, BEGIN_COMMANDS, END_COMMANDS, cmd_table
    ):
        print(
            f"  updated command tiers in {COMMANDS_README.relative_to(repo_home().parent)}"
        )
