"""Generate Codex host instructions from the shared routing and model catalog."""

from pathlib import Path

from sync.catalog import (
    MAP_PATH,
    load_agent_tiers,
    render_agent_routing_body,
    render_agent_tier_table,
)
from sync.common import link_into, parse_model_map, repo_home, write_text_if_changed

CODEX_INSTRUCTIONS = repo_home() / ".codex" / "AGENTS.md"
LIVE_CODEX_INSTRUCTIONS = Path.home() / ".codex" / "AGENTS.md"


def generate_codex_instructions() -> None:
    tiers = parse_model_map(MAP_PATH)
    agents = load_agent_tiers()
    content = """<!-- Generated by home/sync/sync. Edit home/agents/model-map.yaml and
home/protocols/AGENT-ROUTING.md, not this file. -->

# Codex subagent routing

Use Codex's native subagent tools. Shared specialist instructions are generated
as TOML files in `~/.codex/agents/`; each file sets its model and reasoning effort.
Select the named specialist when the host exposes custom agents. If the current
surface only accepts a task prompt, include the specialist's instructions and
pass its model and reasoning effort explicitly using the host's supported API.
Use a fresh or bounded context when the API cannot combine a model override with
full-history inheritance. Wait for the native completion result before checking
the specialist's terminal contract.

The tiers below govern delegated specialists, not the parent session's model.
Do not use Claude's `haiku`/`sonnet`/`opus` aliases or Cursor's `auto` fallback in
Codex. If a configured model is unavailable, report the specific error rather
than silently substituting a different tier.

"""
    content += render_agent_tier_table(tiers, agents) + "\n\n"
    content += render_agent_routing_body(agents).strip() + "\n\n"
    content += """Use the `route-agents` skill for the role selection table. Shared agent
sources and command protocols live in `~/agents/`, `~/commands/`, and
`~/protocols/`. These command documents describe workflows; they are not
automatically registered Codex slash commands.
"""
    if write_text_if_changed(CODEX_INSTRUCTIONS, content):
        print("  generated home/.codex/AGENTS.md")


def install_codex_instructions(
    source: Path = CODEX_INSTRUCTIONS,
    destination: Path = LIVE_CODEX_INSTRUCTIONS,
) -> None:
    """Install without replacing independently maintained user instructions."""
    if destination.is_symlink() and destination.resolve() != source.resolve():
        print(f"  warning: preserving unrelated instructions link {destination}")
        return
    if destination.exists() and not destination.is_symlink():
        print(f"  warning: preserving existing instructions {destination}")
        return
    if link_into(source, destination):
        print(f"  installed Codex instructions → {destination}")
