"""Generate Codex host instructions from the shared routing and model catalog."""

from pathlib import Path

from sync.catalog import (
    MAP_PATH,
    load_agent_tiers,
    render_agent_routing_body,
    render_agent_tier_table,
)
from sync.common import link_into, parse_model_map, repo_home, write_text_if_changed

CODEX_INSTRUCTIONS = repo_home() / ".codex" / "AGENTS.md"
LIVE_CODEX_INSTRUCTIONS = Path.home() / ".codex" / "AGENTS.md"


def generate_codex_instructions() -> None:
    tiers = parse_model_map(MAP_PATH)
    agents = load_agent_tiers()
    content = """<!-- Generated by home/sync/sync. Edit home/agents/model-map.yaml and
home/protocols/AGENT-ROUTING.md, not this file. -->

# Codex subagent routing

"""
    content += render_agent_tier_table(tiers, agents) + "\n\n"
    content += render_agent_routing_body(agents).strip() + "\n\n"
    content += """Use the `route-agents` skill for the role selection table. Shared agent
sources and command protocols live in `~/agents/`, `~/commands/`, and
`~/protocols/`. These command documents describe workflows; they are not
automatically registered Codex slash commands.
"""
    if write_text_if_changed(CODEX_INSTRUCTIONS, content):
        print("  generated home/.codex/AGENTS.md")


def install_codex_instructions(
    source: Path = CODEX_INSTRUCTIONS,
    destination: Path = LIVE_CODEX_INSTRUCTIONS,
) -> None:
    """Install without replacing independently maintained user instructions."""
    if destination.is_symlink() and destination.resolve() != source.resolve():
        print(f"  warning: preserving unrelated instructions link {destination}")
        return
    if destination.exists() and not destination.is_symlink():
        print(f"  warning: preserving existing instructions {destination}")
        return
    if link_into(source, destination):
        print(f"  installed Codex instructions → {destination}")
