"""Generate platform-specific slash commands from home/commands/*.md."""

from __future__ import annotations

import re
import sys
from pathlib import Path

from sync.catalog import generate_catalog
from sync.common import (
    FRONTMATTER_RE,
    expand_pin_tokens,
    link_into,
    parse_model_map,
    prune_stale_md,
    repo_home,
)
from sync.live_cursor import install_all as live_install

COMMANDS_DIR = repo_home() / "commands"
PROTOCOLS_DIR = repo_home() / "protocols"
MAP_PATH = repo_home() / "agents" / "model-map.yaml"
CLAUDE_OUT = repo_home() / ".claude" / "commands"
CURSOR_OUT = repo_home() / ".cursor" / "commands"
CLAUDE_ROOT = repo_home() / ".claude"
CURSOR_PROTOCOLS = repo_home() / ".cursor" / "protocols"

GENERATED_BANNER = (
    "<!-- Generated by home/commands/sync-commands — edit sources in "
    "home/commands/, not this file. -->\n"
)

CLAUDE_FM_ORDER = (
    "description",
    "argument-hint",
    "model",
    "allowed-tools",
    "disable-model-invocation",
)


def split_command(path: Path) -> tuple[dict[str, str], str]:
    text = path.read_text()
    m = FRONTMATTER_RE.match(text)
    if not m:
        raise SystemExit(f"{path}: missing YAML frontmatter")
    fm_raw, body = m.group(1), m.group(2)
    fields: dict[str, str] = {}
    for line in fm_raw.splitlines():
        if not line.strip():
            continue
        kv = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if not kv:
            raise SystemExit(f"{path}: cannot parse frontmatter line: {line!r}")
        fields[kv.group(1)] = kv.group(2)
    if "tier" not in fields:
        raise SystemExit(f"{path}: missing required `tier` field (cheap|mid|strong)")
    if "description" not in fields:
        raise SystemExit(f"{path}: missing required `description` field")
    return fields, body


def render_claude_frontmatter(fields: dict[str, str], model: str) -> str:
    lines = ["---"]
    emitted: set[str] = set()
    for key in CLAUDE_FM_ORDER:
        if key == "model":
            lines.append(f"model: {model}")
            emitted.add("model")
            continue
        if key in fields:
            lines.append(f"{key}: {fields[key]}")
            emitted.add(key)
    for key, val in fields.items():
        if key in emitted or key == "tier":
            continue
        lines.append(f"{key}: {val}")
    lines.append("---")
    return "\n".join(lines) + "\n"


def rewrite_protocol_links(body: str) -> str:
    body = body.replace("`~/.claude/LOOP-PROTOCOL.md`", "`~/protocols/LOOP-PROTOCOL.md`")
    body = body.replace("`~/.claude/HANDOFF-PROTOCOL.md`", "`~/protocols/HANDOFF-PROTOCOL.md`")
    return body


def cursor_preamble(cursor_model: str, tier: str) -> str:
    return (
        f"## Orchestrator model (Cursor)\n"
        f"\n"
        f"Preferred session model for this command: `{cursor_model}` "
        f"(tier `{tier}` via `home/agents/model-map.yaml`). "
        f"Cursor slash commands inherit the chat model — switch the model "
        f"picker to that pin before invoking if the session is on a stronger "
        f"tier. Subagents keep their own frontmatter pins.\n"
        f"\n"
        f"## Arguments (Cursor)\n"
        f"\n"
        f"Positional args from the slash invocation: `$1`, `$2`, `$3`, … .\n"
        f"When this prompt mentions `$ARGUMENTS`, treat it as the joined remainder\n"
        f'`"$1 $2 $3 …"` (trim; empty if no args). Multi-token parsers (e.g. `/dispatch`)\n'
        f"still apply: `$1` = first token (key), later tokens / flags as documented below.\n"
        f"\n"
    )


def to_cursor_body(
    body: str, cursor_model: str, tier: str, tiers: dict[str, dict[str, str]]
) -> str:
    body = rewrite_protocol_links(body)
    body = expand_pin_tokens(body, tiers, "cursor")
    body = re.sub(
        r"\]\(\.\./protocols/(HANDOFF-PROTOCOL|LOOP-PROTOCOL)\.md\)",
        r"](~/protocols/\1.md)",
        body,
    )
    return cursor_preamble(cursor_model, tier) + body


def write_claude(
    name: str,
    fields: dict[str, str],
    body: str,
    model: str,
    tiers: dict[str, dict[str, str]],
) -> Path:
    CLAUDE_OUT.mkdir(parents=True, exist_ok=True)
    body = rewrite_protocol_links(body)
    body = expand_pin_tokens(body, tiers, "claude")
    if not body.startswith("\n"):
        body = "\n" + body
    content = render_claude_frontmatter(fields, model) + GENERATED_BANNER + body
    if not content.endswith("\n"):
        content += "\n"
    path = CLAUDE_OUT / f"{name}.md"
    path.write_text(content)
    return path


def write_cursor(
    name: str,
    body: str,
    cursor_model: str,
    tier: str,
    tiers: dict[str, dict[str, str]],
) -> Path:
    CURSOR_OUT.mkdir(parents=True, exist_ok=True)
    body = to_cursor_body(body, cursor_model, tier, tiers)
    if not body.endswith("\n"):
        body += "\n"
    content = GENERATED_BANNER + "\n" + body
    path = CURSOR_OUT / f"{name}.md"
    path.write_text(content)
    return path


def install_protocols() -> None:
    """Point .claude and .cursor protocol paths at home/protocols/."""
    for name in ("HANDOFF-PROTOCOL.md", "LOOP-PROTOCOL.md"):
        src = PROTOCOLS_DIR / name
        if not src.is_file():
            raise SystemExit(f"missing protocol {src}")
        link_into(src, CLAUDE_ROOT / name, replace_file=True)
        link_into(src, CURSOR_PROTOCOLS / name, replace_file=True)
    live_protocols = Path.home() / "protocols"
    if live_protocols.is_symlink():
        live_protocols.unlink()
    live_protocols.mkdir(parents=True, exist_ok=True)
    for src in sorted(PROTOCOLS_DIR.iterdir()):
        if src.is_file() and not src.is_symlink():
            link_into(src, live_protocols / src.name)


def sync_commands(*, install_live: bool = True) -> int:
    if not PROTOCOLS_DIR.is_dir():
        print(f"missing {PROTOCOLS_DIR}", file=sys.stderr)
        return 1
    if not MAP_PATH.is_file():
        print(f"missing {MAP_PATH}", file=sys.stderr)
        return 1
    tiers = parse_model_map(MAP_PATH)

    sources = sorted(p for p in COMMANDS_DIR.glob("*.md") if p.name != "README.md")
    if not sources:
        print(f"no command sources in {COMMANDS_DIR}", file=sys.stderr)
        return 1

    install_protocols()

    for src in sources:
        fields, body = split_command(src)
        tier = fields["tier"].strip()
        if tier not in tiers:
            print(f"{src}: unknown tier {tier!r}; known: {sorted(tiers)}", file=sys.stderr)
            return 1
        name = src.stem
        claude_model = tiers[tier]["claude"]
        cursor_model = tiers[tier]["cursor"]
        write_claude(name, fields, body, claude_model, tiers)
        write_cursor(name, body, cursor_model, tier, tiers)
        print(f"  {name}: tier={tier} → claude={claude_model} cursor={cursor_model}")

    keep = {p.stem for p in sources}
    for out_dir in (CLAUDE_OUT, CURSOR_OUT):
        prune_stale_md(out_dir, keep, relative_to=repo_home())

    generate_catalog()

    if install_live:
        live_install(agents=False, commands=True, hooks=False, rule=False, cli_config=False)

    print(
        f"synced {len(sources)} commands → "
        f"{CLAUDE_OUT.relative_to(repo_home().parent)} + "
        f"{CURSOR_OUT.relative_to(repo_home().parent)}"
    )
    return 0


def main() -> int:
    return sync_commands(install_live=True)


if __name__ == "__main__":
    raise SystemExit(main())
