local key = require("timopruesse.helpers.keymap")
local claude = require("timopruesse.claude")

-- open agents
key.nnoremap("<leader>zo", function()
	claude.open_claude({ mode = "vsplit" })
end)
key.nnoremap("<leader>zh", function()
	claude.open_claude({ mode = "hsplit" })
end)
key.nnoremap("<leader>zw", function()
	claude.open_claude({ mode = "window" })
end)

-- send selection (new pane)
key.vnoremap("<leader>zs", function()
	claude.send_selection({ mode = "vsplit" })
end)
key.vnoremap("<leader>zp", function()
	claude.prompt_and_send({ mode = "vsplit" })
end)

-- send selection (existing pane)
key.vnoremap("<leader>zr", function()
	claude.send_selection({ existing = true })
end)
key.vnoremap("<leader>zR", function()
	claude.prompt_and_send({ existing = true })
end)

-- send file / diagnostics / git diff
key.nnoremap("<leader>zf", function()
	claude.send_file({ mode = "vsplit" })
end)
key.nnoremap("<leader>zd", function()
	claude.send_diagnostics({ mode = "vsplit" })
end)
key.nnoremap("<leader>zg", function()
	claude.send_git_diff({ mode = "vsplit" })
end)
