local key = require("timopruesse.helpers.keymap")

key.nnoremap("<leader>pl", function()
	require("telescope.builtin").live_grep()
end)
key.nnoremap("<leader>ps", function()
	require("telescope.builtin").grep_string()
end)
key.nnoremap("<C-p>", function()
	require("timopruesse.telescope").project_files()
end)

key.nnoremap("<leader>pb", function()
	require("telescope.builtin").buffers()
end)
key.nnoremap("<leader>qf", function()
	require("telescope.builtin").quickfix()
end)
key.nnoremap("<leader>ll", function()
	require("telescope.builtin").loclist()
end)
key.nnoremap("<leader>jl", function()
	require("telescope.builtin").jumplist()
end)
key.nnoremap("<leader>rl", function()
	require("telescope.builtin").registers()
end)

key.nnoremap("<leader>ds", function()
	require("telescope.builtin").lsp_document_symbols()
end)
key.nnoremap("<leader>ws", function()
	require("telescope.builtin").lsp_workspace_symbols()
end)
key.nnoremap("<leader>ts", function()
	require("telescope.builtin").treesitter()
end)
key.nnoremap("<leader>dg", function()
	require("telescope.builtin").diagnostics()
end)
key.nnoremap("<leader>rf", function()
	require("telescope.builtin").lsp_references()
end)

key.nnoremap("<leader>vrc", function()
	require("timopruesse.telescope").search_dotfiles()
end)
key.nnoremap("<leader>gb", function()
	require("timopruesse.telescope").git_branches()
end)
key.nnoremap("<leader>cl", function()
	require("telescope.builtin").git_commits()
end)
key.nnoremap("<leader>cc", function()
	require("telescope.builtin").git_bcommits()
end)

key.nnoremap("<C-q>", key.exec_command(":Telescope file_browser"))
key.nnoremap("<leader>tf", key.exec_command(":Telescope file_browser path=%:p:h select_buffer=true"))
